In [2]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
# 需要一个地方来存储梯度
x.requires_grad_(True)
x.grad # 默认值是None

In [4]:
# 计算y
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
# 通过调用反向传播函数来自动计算y关于x每个分量的梯度
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4*x

tensor([True, True, True, True])

In [10]:
# Pytorch会累积梯度，需要清除之前的值
x.grad.zero_() # 下划线代表原地（in-place）操作
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [11]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [12]:
# 将某些计算移动到记录的计算图之外
x.grad.zero_()
y = x * x
u = y.detach() # 把y看作常数
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [13]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [14]:
# Python 控制流构建的函数也可计算梯度
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad = True)
d = f(a)
d.backward()
a.grad == d / a

tensor(True)