In [2]:
# 构造一个没有任何参数的自定义层
import torch
from torch import nn
from torch.nn import functional as F

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
# 将层作为组件合并到构建更复杂的模型中
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(5.3551e-09, grad_fn=<MeanBackward0>)

In [4]:
# 带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.0896,  0.3622, -0.6705],
        [ 0.2530, -1.7969, -0.0397],
        [ 0.8075, -0.4183, -0.8414],
        [-1.4875,  0.4670,  0.1119],
        [-0.2533,  0.1837,  2.0835]], requires_grad=True)

In [5]:
# 使用自定义层直接执行正向传播计算
linear(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 1.9585],
        [0.0000, 0.0000, 1.5088]])

In [6]:
# 使用自定义层构建模型
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[12.3821],
        [ 8.1726]])